name = 'ReVise'
license = 'MIT'
licenselink = 'https://github.com/julkar-naim/julkar-naim.com/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/julkar-naim/julkar-naim.com'

[author]
  name = 'Julkar Naim'
  homepage = 'https://julkar-naim.com'

